# Generated by Django 5.2.6 on 2025-10-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='role',
            new_name='sender',
        ),
    ]
