# Generated by Django 5.2.6 on 2025-09-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_scheduled_time_patient_surgeon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bp_diastolic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp_systolic',
        ),
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.CharField(default=0, help_text='Blood Pressure (e.g., 120/80)', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='parity',
            field=models.PositiveIntegerField(default=0, help_text='Number of births (parity)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='booking',
            field=models.CharField(choices=[('first_trimester', 'First Trimester'), ('second_trimester', 'Second Trimester'), ('third_trimester', 'Third Trimester'), ('unbooked', 'Unbooked')], default='unbooked', max_length=20),
        ),
    ]
