# Generated by Django 5.2.6 on 2025-09-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_bp_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_pregnancy_fetal',
            field=models.JSONField(default=list, help_text='List of current pregnancy fetal conditions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_pregnancy_menternal',
            field=models.JSONField(default=list, help_text='List of current pregnancy maternal conditions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='menternal_medical',
            field=models.JSONField(default=list, help_text='List of maternal medical conditions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='obstetric_history',
            field=models.JSONField(default=list, help_text='List of obstetric history conditions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='social',
            field=models.JSONField(default=list, help_text='List of social factors'),
        ),
    ]
