# Generated by Django 5.2.6 on 2025-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_current_pregnancy_fetal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cervical_dilatation_at_admission',
            field=models.FloatField(blank=True, help_text='Cervical dilatation at admission in cm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fully_dilated_cervix',
            field=models.BooleanField(default=False, help_text='Whether cervix is fully dilated'),
        ),
        migrations.AddField(
            model_name='patient',
            name='labor_duration_hours',
            field=models.FloatField(blank=True, help_text='Total labor duration in hours', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time_of_admission',
            field=models.DateTimeField(blank=True, help_text='Time of admission to hospital', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time_of_cervix_fully_dilated',
            field=models.DateTimeField(blank=True, help_text='Time when cervix became fully dilated', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time_of_delivery',
            field=models.DateTimeField(blank=True, help_text='Time of delivery', null=True),
        ),
    ]
