# Generated by Django 5.2.6 on 2025-09-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_cervical_dilatation_at_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='acute_kidney_injury',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='apgar_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_injuries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_loss',
            field=models.CharField(blank=True, choices=[('less_than_500', 'Less than 500'), ('501_1000', '501-1000'), ('1001_1500', '1001-1500'), ('more_than_1500', 'More than 1500')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_transfusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='ceasrean_hysterectomy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='cervix_favrable_for_induction',
            field=models.CharField(blank=True, choices=[('unfavorable_bishop_score_less_6', 'Unfavorable (Bishop score <6)'), ('favorable_bishop_score_6_or_more', 'Favorable (Bishop score ≥6)')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='congenital_anomalies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cs_indication',
            field=models.CharField(blank=True, choices=[('fetal_distress', 'Fetal distress'), ('failure_to_progress', 'Failure to progress'), ('cord_prolapse', 'Cord prolapse'), ('chorioamnionitis', 'Chorioamnionitis'), ('other_fetal_iugr', 'Other(Fetal),IUGR'), ('breech_baby', 'Breech baby'), ('multiple_pregnancy', 'Multiple pregnancy'), ('maternal_request_no_medical_reason', 'Maternal request (no medical reason)'), ('pre_eclampsia_eclampsia_hellp', 'Pre-eclampsia/eclampsia/HELLP'), ('maternal_medical_disease', 'Maternal medical disease'), ('placenta_praevia_actively_bleeding', 'Placenta praevia, actively bleeding'), ('placenta_praevia_not_actively_bleeding', 'Placenta praevia, not actively bleeding'), ('aph_intrapartum_haemorrhage', 'APH/Intrapartum haemorrhage'), ('placental_abruption', 'Placental abruption'), ('uterine_rupture', 'Uterine rupture'), ('other_maternal', 'Other (maternal)'), ('refusal_of_tolac', 'Refusal of TOLAC'), ('failed_tolac', 'Failed TOLAC'), ('feto_pelvic_disproportion', 'Feto-Pelvic Disproportion'), ('abnormal_lie_presentation_other_than_breech', 'Abnormal lie/presentation other than breech'), ('repeated_cs', 'Repeated CS'), ('failed_iol', 'Failed IOL'), ('infertility_precious_baby', 'Infertility(precious baby)'), ('repeated_cs_in_labor', 'Repeated CS in labor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ctg_category',
            field=models.CharField(blank=True, choices=[('category_i_normal_reassuring', 'Category I – Normal/reassuring'), ('category_ii_suspicious', 'Category II – Suspicious'), ('category_iii_pathological', 'Category III – Pathological')], max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='eclampsia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_ceasrean_section',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='estimated_fetal_weight_by_gm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fetus_number',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('twin', 'Twin'), ('triplete', 'Triplet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ga_interval',
            field=models.CharField(blank=True, choices=[('less_than_37_weeks', 'Less than 37 weeks'), ('37_to_40_weeks', '37 to 40 weeks'), ('more_than_40_weeks', 'More than 40 weeks')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hb_g_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hellp_syndrome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='icu_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='icu_admission_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='indication_of_induction',
            field=models.CharField(blank=True, choices=[('post_term_pregnancy_41_weeks', 'Post-term pregnancy ≥41 weeks'), ('prelabor_rupture_of_membranes_prom', 'Prelabor rupture of membranes (PROM)'), ('oligohydramnios', 'Oligohydramnios'), ('gestational_hypertension', 'Gestational hypertension'), ('preeclampsia_diabetes_mellitus', 'Preeclampsia Diabetes mellitus'), ('intrauterine_growth_restriction_iugr', 'Intrauterine growth restriction (IUGR)'), ('intrauterine_fetal_demise_iufd', 'Intrauterine fetal demise (IUFD)'), ('chorioamnionitis', 'Chorioamnionitis'), ('elective_social_other', 'Elective (social/other)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='induction_method',
            field=models.CharField(blank=True, choices=[('prostaglandin_e2_gel_pessary', 'Prostaglandin E2 (gel/pessary)'), ('prostaglandin_e1_misoprostol', 'Prostaglandin E1 (misoprostol)'), ('oxytocin_infusion', 'Oxytocin infusion'), ('amniotomy_arm', 'Amniotomy (ARM)'), ('foley_catheter', 'Foley catheter'), ('combined_method_mechanical_pharmacological', 'Combined method (mechanical + pharmacological)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='infection_endometritis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='instrumental_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='liquor',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('oligohydraminos', 'Oligohydramnios'), ('polihydraminos', 'Polihydramnios')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='liquor_2',
            field=models.CharField(blank=True, choices=[('clear', 'Clear'), ('meconium_stained_thin', 'Meconium-stained (thin)'), ('meconium_stained_thick', 'Meconium-stained (thick)'), ('blood_stained', 'Blood-stained'), ('absent_anhydramnios_dry_tap', 'Absent (anhydramnios/dry tap)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='los_by_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='maternal_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='membrane_status',
            field=models.CharField(blank=True, choices=[('intact', 'Intact'), ('ruptured_spontaneous', 'Ruptured – spontaneous'), ('ruptured_artificial_arm', 'Ruptured – artificial (ARM)')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mode_of_delivery',
            field=models.CharField(blank=True, choices=[('nvd', 'NVD'), ('cs', 'C.S')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='neonatal_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='nicu_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_maternal_morbidity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='parity_status',
            field=models.CharField(blank=True, choices=[('primigravida', 'Primigravida'), ('multipara', 'Multipara')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='perineum_integrity',
            field=models.CharField(blank=True, choices=[('intact', 'Intact'), ('episotomy', 'Episotomy'), ('1st_2nd_tear', '1st/2nd Tear'), ('3rd_4th_tear', '3rd/4th Tear'), ('episotomy_3rd_4th', 'Episotomy+3rd,4th')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='placenta_location',
            field=models.CharField(blank=True, choices=[('upper', 'Upper'), ('lower', 'Lower'), ('covering_cervix', 'Covering Cervix')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='placental_abruption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='platelets_x10e9l',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='presentation',
            field=models.CharField(blank=True, choices=[('cephlic', 'Cephalic'), ('preech', 'Breech'), ('transverse', 'Transverse'), ('oblique', 'Oblique')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='preterm_birth_less_37_weeks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='prolonged_hospital_stay_more_4_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='readmission_within_30d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='robson_classification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rupture_duration_hour',
            field=models.CharField(blank=True, choices=[('less_than_6_hours', '<6 hours'), ('6_12_hours', '6–12 hours'), ('12_18_hours', '12–18 hours'), ('18_24_hours', '18–24 hours'), ('more_than_24_hours_prolonged_rupture', '>24 hours (prolonged rupture)'), ('still_intact', 'Still intact')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rupture_uterus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='sever_pph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_number_of_cs',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_of_anasthesia',
            field=models.CharField(blank=True, choices=[('ga', 'GA'), ('spinal', 'Spinal'), ('epidural', 'Epidural')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_of_cs',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('elective', 'Elective')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_of_labor',
            field=models.CharField(blank=True, choices=[('spontenous_labor', 'Spontaneous Labor'), ('iol', 'IOL'), ('pre_labour_cesarean', 'Pre-labour Cesarean'), ('no_labour_pain', 'No Labour Pain')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='vbac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='vte_postpartum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward_admissin_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='wound_complication',
            field=models.BooleanField(default=False),
        ),
    ]
