# Generated by Django 5.2.6 on 2025-10-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_acute_kidney_injury_patient_apgar_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='baby_file_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
