# Generated by Django 5.2.6 on 2025-10-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_baby_file_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='baby_file_number',
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=100, null=True)),
                ('new_born_viability', models.BooleanField(default=True)),
                ('preterm_birth_less_37_weeks', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('birth_weight', models.FloatField(blank=True, null=True)),
                ('apgar_score', models.PositiveIntegerField(blank=True, null=True)),
                ('neonatal_death', models.BooleanField(default=False)),
                ('congenital_anomalies', models.BooleanField(default=False)),
                ('hie', models.BooleanField(default=False)),
                ('nicu_admission', models.BooleanField(default=False)),
                ('birth_injuries', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='patients.patient')),
            ],
        ),
    ]
