# Generated by Django 5.2.6 on 2025-11-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patient_baby_file_number_baby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('team_leader', 'Team Leader'), ('nurse', 'Nurse')], default='patient', max_length=20),
        ),
    ]
