# Generated by Django 5.2.6 on 2025-11-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presentation',
            field=models.CharField(blank=True, choices=[('cephlic', 'Cephalic'), ('breech', 'Breech'), ('transverse', 'Transverse'), ('oblique', 'Oblique')], max_length=20, null=True),
        ),
    ]
