# Generated by Django 5.2.6 on 2025-11-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_is_discharged_alter_patient_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
