# Generated by Django 5.2.6 on 2025-11-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_discharged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_moved_to_cs',
            field=models.BooleanField(default=False),
        ),
    ]
