# Generated by Django 5.2.6 on 2025-12-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patient_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='liquor',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('oligohydraminos', 'Oligohydramnios'), ('polyhydraminos', 'Polyhydraminos')], max_length=20, null=True),
        ),
    ]
